apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-consumer
  namespace: event-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator-consumer
  template:
    metadata:
      labels:
        app: aggregator-consumer
    spec:
      containers:
        - name: consumer
          image: h1shamdev/aggregator-consumer:latest
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: guest
            - name: RABBITMQ_PASSWORD
              value: guest
          volumeMounts:
            - name: aws-credentials
              mountPath: /root/.aws/
              readOnly: true

      volumes:
        - name: aws-credentials
          secret:
            secretName: aws-credentials

