apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-producer
  namespace: event-pipeline
spec:
  selector:
    matchLabels:
      app: aggregator-producer
  template:
    metadata:
        labels:
          app: aggregator-producer
    spec:
      containers:
        - name: producer
          image: h1shamdev/aggregator-producer:latest
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: guest
            - name: RABBITMQ_PASSWORD
              value: guest

